version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - '6380:6379'
      
  # worker:
  #   build:
  #     context: ./
  #   command: ['celery', '-A', 'auto_subs', 'worker', '--loglevel=INFO']
  #   depends_on:
  #     - redis


